import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Starting seed...');

  const admin = await prisma.user.upsert({
    where: { email: 'admin@trustauto.co.ke' },
    update: {},
    create: {
      email: 'admin@trustauto.co.ke',
      password: '$2a$10$BEytcMDkTdWgFRedt2fl1O.Etc3jpY61ppFPsKa5LSZVRcQwWkFKS',
      name: 'Admin User',
      role: 'ADMIN',
    },
  });

  console.log('Created admin user:', admin.email);

  const vehicles = [
    {
      make: 'Toyota',
      model: 'Camry',
      year: 2023,
      priceKES: 4275000,
      mileage: 5200,
    bodyType: 'SEDAN' as const,
    fuelType: 'GASOLINE' as const,
    transmission: 'Automatic',
    drivetrain: 'FWD',
    exteriorColor: 'Midnight Black Metallic',
    interiorColor: 'Black',
    engine: '2.5L I4',
    vin: '4T1B11HK6PU123456',
    status: 'USED' as const,
    featured: true,
    description: 'Experience reliability and comfort with this 2023 Toyota Camry. With low mileage and a pristine condition, it offers a smooth and efficient ride. Features include a touchscreen infotainment system, Apple CarPlay, and Toyota Safety Sense 2.5+. Perfect for daily commutes and long road trips alike.',
    imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    make: 'Ford',
    model: 'F-150',
    year: 2024,
    priceKES: 6750000,
    mileage: 15,
    bodyType: 'TRUCK' as const,
    fuelType: 'GASOLINE' as const,
    transmission: 'Automatic',
    drivetrain: '4WD',
    exteriorColor: 'Iconic Silver',
    interiorColor: 'Medium Stone',
    engine: '3.5L V6 EcoBoost',
    vin: '1FTFW1E58RKF12345',
    status: 'NEW' as const,
    featured: true,
    description: 'The 2024 Ford F-150 is built for work and play. This brand-new model features the powerful 3.5L EcoBoost V6 engine, a spacious interior with the latest SYNC 4 technology, and Pro Power Onboard to turn your truck into a mobile generator. Ready for any challenge.',
    imageUrl: 'https://images.unsplash.com/photo-1563411065591-3e7d8c2c5e46?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    make: 'Honda',
    model: 'CR-V',
    year: 2022,
    priceKES: 4650000,
    mileage: 18500,
    bodyType: 'SUV' as const,
    fuelType: 'GASOLINE' as const,
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Platinum White Pearl',
      interiorColor: 'Gray',
      engine: '1.5L Turbo I4',
      vin: '2HKRW2H52NH678901',
      status: 'CERTIFIED_PRE_OWNED' as const,
      featured: false,
      description: 'A versatile and reliable SUV, this 2022 Honda CR-V is perfect for families. It comes with a certified pre-owned warranty, all-wheel drive for all-weather confidence, and a fuel-efficient turbocharged engine. Spacious cargo area and top safety ratings.',
      imageUrl: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'BMW',
      model: '330i',
      year: 2023,
      priceKES: 6300000,
      mileage: 9800,
      bodyType: 'SEDAN' as const,
      fuelType: 'GASOLINE' as const,
      transmission: 'Automatic',
      drivetrain: 'RWD',
      exteriorColor: 'Alpine White',
      interiorColor: 'Black',
      engine: '2.0L Turbo I4',
      vin: 'WBA33AK09PD234567',
      status: 'USED' as const,
      featured: true,
      description: 'Enjoy the ultimate driving machine in this 2023 BMW 330i. It blends sporty performance with everyday luxury. Features include the iDrive infotainment system, premium sound, and advanced driver-assistance features. A thrilling yet sophisticated ride.',
      imageUrl: 'https://images.unsplash.com/photo-1617654112361-92000d48d477?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Tesla',
      model: 'Model Y',
      year: 2023,
      priceKES: 7800000,
      mileage: 12000,
      bodyType: 'SUV' as const,
      fuelType: 'ELECTRIC' as const,
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Deep Blue Metallic',
      interiorColor: 'Black',
      engine: 'Dual Motor AWD',
      vin: '5YJ3E1EA5PF123456',
      status: 'USED' as const,
      featured: false,
      description: 'Step into the future with this 2023 Tesla Model Y. This all-electric SUV offers incredible acceleration, a minimalist high-tech interior, and access to the Supercharger network. Autopilot capabilities and over-the-air updates keep it at the cutting edge.',
      imageUrl: 'https://images.unsplash.com/photo-1617704548629-94655d379f5e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Chevrolet',
      model: 'Equinox',
      year: 2021,
      priceKES: 3525000,
      mileage: 31000,
      bodyType: 'SUV' as const,
      fuelType: 'GASOLINE' as const,
      transmission: 'Automatic',
      drivetrain: 'FWD',
      exteriorColor: 'Summit White',
      interiorColor: 'Jet Black',
      engine: '1.5L Turbo I4',
      vin: '2GNAXHEV4M6123456',
      status: 'ON_SALE' as const,
      featured: false,
      description: 'Great value in a compact SUV! This 2021 Chevrolet Equinox is clean, reliable, and fuel-efficient. It comes with a user-friendly infotainment system and plenty of cargo space. Priced to sell, it\'s the perfect practical choice.',
      imageUrl: 'https://images.unsplash.com/photo-1593941707882-a5bac6861d75?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Jeep',
      model: 'Wrangler',
      year: 2022,
      priceKES: 5700000,
      mileage: 15000,
      bodyType: 'SUV' as const,
      fuelType: 'GASOLINE' as const,
      transmission: 'Manual',
      drivetrain: '4WD',
      exteriorColor: 'Firecracker Red',
      interiorColor: 'Black',
      engine: '3.6L V6',
      vin: '1C4HJXFG6NW789012',
      status: 'USED' as const,
      featured: false,
      description: 'Unleash your adventurous side with this 2022 Jeep Wrangler. Equipped with a manual transmission and legendary 4x4 capability, it\'s ready for trails or city streets. The removable top and doors offer an open-air experience like no other.',
      imageUrl: 'https://images.unsplash.com/photo-1604108415419-6d4bd73a1c2c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Mazda',
      model: 'CX-5',
      year: 2023,
      priceKES: 4800000,
      mileage: 7000,
      bodyType: 'SUV' as const,
      fuelType: 'GASOLINE' as const,
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Soul Red Crystal',
      interiorColor: 'Parchment',
      engine: '2.5L I4',
      vin: 'JM3KFBDM9P0123456',
      status: 'CERTIFIED_PRE_OWNED' as const,
      featured: false,
      description: 'Style and substance define the 2023 Mazda CX-5. With its upscale interior and responsive handling, it feels more like a luxury vehicle. The i-Activsense safety package and Apple CarPlay integration make every drive safer and more enjoyable.',
      imageUrl: 'https://images.unsplash.com/photo-1583121274602-3e2820c6f88f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Hyundai',
      model: 'Elantra',
      year: 2024,
      priceKES: 3300000,
      mileage: 50,
      bodyType: 'SEDAN' as const,
      fuelType: 'GASOLINE' as const,
      transmission: 'Automatic',
      drivetrain: 'FWD',
      exteriorColor: 'Phantom Black',
      interiorColor: 'Gray',
      engine: '2.0L I4',
      vin: 'KMHLJ4AE2RA123456',
      status: 'NEW' as const,
      featured: false,
      description: 'A brand-new 2024 Hyundai Elantra, offering modern tech and an impressive warranty. Its bold design stands out, while the fuel-efficient engine and comfortable ride make it an excellent daily driver. Comes with a suite of standard safety features.',
      imageUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Subaru',
      model: 'Outback',
      year: 2022,
      priceKES: 4500000,
      mileage: 21000,
      bodyType: 'WAGON' as const,
      fuelType: 'GASOLINE' as const,
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Crystal White Pearl',
      interiorColor: 'Ivory',
      engine: '2.5L Boxer 4',
      vin: '4S4BTACC6N3123456',
      status: 'USED' as const,
      featured: false,
      description: 'The go-anywhere 2022 Subaru Outback. Standard Symmetrical All-Wheel Drive gives you confidence in any weather. With its rugged design and wagon-like utility, it\'s perfect for outdoor enthusiasts and families alike.',
      imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Mercedes-Benz',
      model: 'C-Class',
      year: 2023,
      priceKES: 7200000,
      mileage: 11000,
      bodyType: 'SEDAN' as const,
      fuelType: 'GASOLINE' as const,
      transmission: 'Automatic',
      drivetrain: 'RWD',
      exteriorColor: 'Iridium Silver Metallic',
      interiorColor: 'Black',
      engine: '2.0L Turbo I4',
      vin: 'W1KRF8DB7PR123456',
      status: 'USED' as const,
      featured: false,
      description: 'Elegance and innovation in the 2023 Mercedes-Benz C-Class. The interior is a marvel of modern design with a large vertical touchscreen. It delivers a refined, comfortable ride with responsive performance when you need it.',
      imageUrl: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Ram',
      model: '1500',
      year: 2021,
      priceKES: 5250000,
      mileage: 40000,
      bodyType: 'TRUCK' as const,
      fuelType: 'GASOLINE' as const,
      transmission: 'Automatic',
      drivetrain: '4WD',
      exteriorColor: 'Bright White',
      interiorColor: 'Black',
      engine: '5.7L HEMI V8',
      vin: '1C6RR7GT5MN123456',
      status: 'ON_SALE' as const,
      featured: false,
      description: 'Get the power of a HEMI V8 with this 2021 Ram 1500. Known for its smooth ride and luxurious interior, this truck is as comfortable as it is capable. A great deal on a feature-packed truck.',
      imageUrl: 'https://images.unsplash.com/photo-1554224154-260325c0594e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Nissan',
      model: 'Rogue',
      year: 2023,
      priceKES: 4350000,
      mileage: 8000,
      bodyType: 'SUV' as const,
      fuelType: 'GASOLINE' as const,
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Gun Metallic',
      interiorColor: 'Charcoal',
      engine: '1.5L Turbo I4',
      vin: '5N1AT3BV4PC123456',
      status: 'USED' as const,
      featured: false,
      description: 'A practical and tech-savvy choice, the 2023 Nissan Rogue features a spacious interior and a large digital display. ProPILOT Assist makes highway driving less stressful. It\'s a well-rounded compact SUV for the modern family.',
      imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Audi',
      model: 'Q5',
      year: 2022,
      priceKES: 6150000,
      mileage: 18000,
      bodyType: 'SUV' as const,
      fuelType: 'GASOLINE' as const,
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Navarra Blue Metallic',
      interiorColor: 'Gray',
      engine: '2.0L Turbo I4',
      vin: 'WA1CFAF29ND123456',
      status: 'CERTIFIED_PRE_OWNED' as const,
      featured: false,
      description: 'Experience premium German engineering with this 2022 Audi Q5. Its Quattro all-wheel-drive system provides sure-footed handling, while the cabin is a haven of luxury and technology. A perfect blend of performance and sophistication.',
      imageUrl: 'https://images.unsplash.com/photo-1617654112361-92000d48d477?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Ford',
      model: 'Mustang',
      year: 2023,
      priceKES: 5850000,
      mileage: 5000,
      bodyType: 'COUPE' as const,
      fuelType: 'GASOLINE' as const,
      transmission: 'Manual',
      drivetrain: 'RWD',
      exteriorColor: 'Race Red',
      interiorColor: 'Black',
      engine: '2.3L EcoBoost I4',
      vin: '1FA6P8CF0P5123456',
      status: 'USED' as const,
      featured: false,
      description: 'Pure American muscle. This 2023 Ford Mustang with a manual transmission offers an engaging and thrilling driving experience. The turbocharged EcoBoost engine provides plenty of power, and its iconic styling turns heads everywhere.',
      imageUrl: 'https://images.unsplash.com/photo-1583121274602-3e2820c6f88f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Kia',
      model: 'Telluride',
      year: 2023,
      priceKES: 5550000,
      mileage: 12000,
      bodyType: 'SUV' as const,
      fuelType: 'GASOLINE' as const,
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Evergreen Silver',
      interiorColor: 'Black',
      engine: '3.8L V6',
      vin: '5XYP5DHC1PG123456',
      status: 'USED' as const,
      featured: false,
      description: 'The award-winning Kia Telluride offers a luxurious and spacious three-row cabin without the luxury price tag. This 2023 model is packed with features and provides a comfortable, quiet ride for the whole family.',
      imageUrl: 'https://images.unsplash.com/photo-1593941707882-a5bac6861d75?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Lexus',
      model: 'RX 350',
      year: 2021,
      priceKES: 6600000,
      mileage: 28000,
      bodyType: 'SUV' as const,
      fuelType: 'GASOLINE' as const,
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Nebula Gray Pearl',
      interiorColor: 'NuLuxe',
      engine: '3.5L V6',
      vin: '2T2BZMCA1MC123456',
      status: 'CERTIFIED_PRE_OWNED' as const,
      featured: false,
      description: 'Refined luxury and legendary reliability. This 2021 Lexus RX 350 delivers an exceptionally smooth and quiet ride. The cabin is impeccably crafted with high-quality materials, and it comes with the peace of mind of a Lexus CPO warranty.',
      imageUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Toyota',
      model: 'Prius',
      year: 2023,
      priceKES: 4050000,
      mileage: 15000,
      bodyType: 'HATCHBACK' as const,
      fuelType: 'HYBRID' as const,
      transmission: 'Automatic',
      drivetrain: 'FWD',
      exteriorColor: 'Cutting Edge',
      interiorColor: 'Black',
      engine: '2.0L Hybrid I4',
      vin: 'JTDKAMFV1P3123456',
      status: 'USED' as const,
      featured: false,
      description: 'Save money on gas with this stylish and efficient 2023 Toyota Prius. The latest generation features a futuristic design and a more powerful hybrid system. It\'s the perfect choice for the eco-conscious driver who doesn\'t want to sacrifice style.',
      imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'GMC',
      model: 'Sierra 1500',
      year: 2024,
      priceKES: 8250000,
      mileage: 10,
      bodyType: 'TRUCK' as const,
      fuelType: 'DIESEL' as const,
      transmission: 'Automatic',
      drivetrain: '4WD',
      exteriorColor: 'Dark Sky Metallic',
      interiorColor: 'Jet Black',
      engine: '3.0L Duramax Turbo-Diesel I6',
      vin: '1GTU9DEL4RZ123456',
      status: 'NEW' as const,
      featured: true,
      description: 'This brand-new 2024 GMC Sierra 1500 is the pinnacle of truck luxury and capability. The Duramax diesel engine provides massive torque for towing, while the premium Denali trim offers a multi-pro tailgate, a massive infotainment screen, and unparalleled comfort.',
      imageUrl: 'https://images.unsplash.com/photo-1554224154-260325c0594e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Volkswagen',
      model: 'Atlas',
      year: 2022,
      priceKES: 4950000,
      mileage: 25000,
      bodyType: 'SUV' as const,
      fuelType: 'GASOLINE' as const,
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Pyramid Silver Metallic',
      interiorColor: 'Vienna Leather',
      engine: '3.6L VR6',
      vin: '1V2WR2CA7NC123456',
      status: 'USED' as const,
      featured: false,
      description: 'The family hauler redefined. This 2022 VW Atlas offers a massive and flexible interior with three rows of seating. The powerful V6 engine and smooth ride make it a great long-distance cruiser for the entire family.',
      imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Porsche',
      model: 'Macan',
      year: 2023,
      priceKES: 9300000,
      mileage: 7000,
      bodyType: 'SUV' as const,
      fuelType: 'GASOLINE' as const,
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Carmine Red',
      interiorColor: 'Black',
      engine: '2.0L Turbo I4',
      vin: 'WP1AB2A58PDA12345',
      status: 'CERTIFIED_PRE_OWNED' as const,
      featured: false,
      description: 'The sports car of compact SUVs. This 2023 Porsche Macan combines thrilling performance with everyday practicality. Its precise handling and powerful engine make every drive an event, wrapped in a luxurious and well-built package.',
      imageUrl: 'https://images.unsplash.com/photo-1617654112361-92000d48d477?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Honda',
      model: 'Accord',
      year: 2024,
      priceKES: 3900000,
      mileage: 5,
      bodyType: 'SEDAN' as const,
      fuelType: 'HYBRID' as const,
      transmission: 'Automatic',
      drivetrain: 'FWD',
      exteriorColor: 'Meteorite Gray Metallic',
      interiorColor: 'Black',
      engine: '2.0L Hybrid I4',
      vin: '1HGCV1F34RA123456',
      status: 'NEW' as const,
      featured: false,
      description: 'All-new for 2024, the Honda Accord Hybrid sets the standard for sedans. It offers exceptional fuel economy, a sophisticated and spacious interior, and a smooth, quiet ride. A smart and stylish choice for a new car.',
      imageUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Ford',
      model: 'Explorer',
      year: 2021,
      priceKES: 4425000,
      mileage: 35000,
      bodyType: 'SUV' as const,
      fuelType: 'GASOLINE' as const,
      transmission: 'Automatic',
      drivetrain: 'RWD',
      exteriorColor: 'Agate Black Metallic',
      interiorColor: 'Sandstone',
      engine: '2.3L EcoBoost I4',
      vin: '1FM5K8GC1MGA12345',
      status: 'ON_SALE' as const,
      featured: false,
      description: 'A versatile three-row SUV at a great price. This 2021 Ford Explorer has room for the whole family and their gear. The powerful EcoBoost engine provides plenty of get-up-and-go, and the rear-wheel-drive platform offers a balanced ride.',
      imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    },
    {
      make: 'Genesis',
      model: 'G70',
      year: 2023,
      priceKES: 6000000,
      mileage: 9000,
      bodyType: 'SEDAN' as const,
      fuelType: 'GASOLINE' as const,
      transmission: 'Automatic',
      drivetrain: 'RWD',
      exteriorColor: 'Savannah Metallic',
      interiorColor: 'Dapper Red',
      engine: '2.0L Turbo I4',
      vin: 'KMHTC6AE2PU123456',
      status: 'USED' as const,
      featured: false,
      description: 'A true sports sedan with luxury appointments. The 2023 Genesis G70 offers rear-wheel-drive dynamics, a powerful engine, and a stunning interior design. With features like a limited-slip differential and Brembo brakes, it\'s built for driving enthusiasts.',
      imageUrl: 'https://images.unsplash.com/photo-1617654112361-92000d48d477?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    },
  ];

  for (const vehicle of vehicles) {
    await prisma.vehicle.upsert({
      where: { vin: vehicle.vin },
      update: {},
      create: vehicle,
    });
  }

  console.log(`Created ${vehicles.length} vehicles`);
  console.log('Seed completed successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
